In [1]:
import numpy as np
import tensorflow as tf


C:\Peter\Anaconda36\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [4]:
a1= np.array([[0., 1., 2., 3., 4.],  [5., 6., 7., 8., 9.]])
a2= np.array([[10.,12.,14.,16.,18.], [20.,22.,24.,26.,28.]])
a3= np.array([[ 6., 8.,10.,12.,14.], [16.,18.,20.,22.,24.]])
a = [a1,  a2,  a3]
print('a1:\n', a1)
print('a2:\n', a2)
print('a3:\n', a3)
print('a:\n', a)

a1:
 [[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]
a2:
 [[10. 12. 14. 16. 18.]
 [20. 22. 24. 26. 28.]]
a3:
 [[ 6.  8. 10. 12. 14.]
 [16. 18. 20. 22. 24.]]
a:
 [array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.]]), array([[10., 12., 14., 16., 18.],
       [20., 22., 24., 26., 28.]]), array([[ 6.,  8., 10., 12., 14.],
       [16., 18., 20., 22., 24.]])]


In [6]:
b1= np.array([[50.,52.,54.,56.,58.], [60., 62., 64., 66., 68.]])
b2= np.array([[30.,32.,34.,36.,38.], [40., 42., 44., 46., 48.]])
b3= np.array([[12.,14.,16.,18.,20.], [22., 24., 26., 28., 30.]])
b = [b1,  b2,  b3]
print('b1:\n', b1)
print('b2:\n', b2)
print('b3:\n', b3)
print('b:\n', b)

b1:
 [[50. 52. 54. 56. 58.]
 [60. 62. 64. 66. 68.]]
b2:
 [[30. 32. 34. 36. 38.]
 [40. 42. 44. 46. 48.]]
b3:
 [[12. 14. 16. 18. 20.]
 [22. 24. 26. 28. 30.]]
b:
 [array([[50., 52., 54., 56., 58.],
       [60., 62., 64., 66., 68.]]), array([[30., 32., 34., 36., 38.],
       [40., 42., 44., 46., 48.]]), array([[12., 14., 16., 18., 20.],
       [22., 24., 26., 28., 30.]])]


In [7]:
a_array_325= np.array(a)
b_array_325= np.array(b)
print('a_array_325:\n', a_array_325)
print('b_array_325:\n', b_array_325)

a_array_325:
 [[[ 0.  1.  2.  3.  4.]
  [ 5.  6.  7.  8.  9.]]

 [[10. 12. 14. 16. 18.]
  [20. 22. 24. 26. 28.]]

 [[ 6.  8. 10. 12. 14.]
  [16. 18. 20. 22. 24.]]]
b_array_325:
 [[[50. 52. 54. 56. 58.]
  [60. 62. 64. 66. 68.]]

 [[30. 32. 34. 36. 38.]
  [40. 42. 44. 46. 48.]]

 [[12. 14. 16. 18. 20.]
  [22. 24. 26. 28. 30.]]]


In [8]:
a_array_235 = np.reshape(np.hstack(a_array_325), (2, 3, 5))
b_array_235 = np.reshape(np.hstack(b_array_325), (2, 3, 5))
print('a_array_235:\n', a_array_235)
print('b_array_235:\n', b_array_235)

a_array_235:
 [[[ 0.  1.  2.  3.  4.]
  [10. 12. 14. 16. 18.]
  [ 6.  8. 10. 12. 14.]]

 [[ 5.  6.  7.  8.  9.]
  [20. 22. 24. 26. 28.]
  [16. 18. 20. 22. 24.]]]
b_array_235:
 [[[50. 52. 54. 56. 58.]
  [30. 32. 34. 36. 38.]
  [12. 14. 16. 18. 20.]]

 [[60. 62. 64. 66. 68.]
  [40. 42. 44. 46. 48.]
  [22. 24. 26. 28. 30.]]]


In [11]:
a235_m_b235 = (a_array_235 * b_array_235)
print('a235_m_b235:', a235_m_b235.shape,'\n', a235_m_b235)

a235_m_b235: (2, 3, 5) 
 [[[   0.   52.  108.  168.  232.]
  [ 300.  384.  476.  576.  684.]
  [  72.  112.  160.  216.  280.]]

 [[ 300.  372.  448.  528.  612.]
  [ 800.  924. 1056. 1196. 1344.]
  [ 352.  432.  520.  616.  720.]]]


In [13]:
ab235_avg = tf.reduce_sum(a235_m_b235)/(2*3)
sess = tf.Session()
ab235_avg_v = sess.run(ab235_avg)
print('ab235_avg:\n', ab235_avg_v)
sess.close()

ab235_avg:
 2340.0


In [15]:
rev_a_325 = np.reshape(np.hstack(a_array_235), (3, 2, 5))
rev_b_325 = np.reshape(np.hstack(b_array_235), (3, 2, 5))
print('rev_a_325 ',rev_a_325.shape, '\n', rev_a_325)                       
print('rev_b_325 ',rev_b_325.shape, '\n', rev_b_325)

rev_a_325  (3, 2, 5) 
 [[[ 0.  1.  2.  3.  4.]
  [ 5.  6.  7.  8.  9.]]

 [[10. 12. 14. 16. 18.]
  [20. 22. 24. 26. 28.]]

 [[ 6.  8. 10. 12. 14.]
  [16. 18. 20. 22. 24.]]]
rev_b_325  (3, 2, 5) 
 [[[50. 52. 54. 56. 58.]
  [60. 62. 64. 66. 68.]]

 [[30. 32. 34. 36. 38.]
  [40. 42. 44. 46. 48.]]

 [[12. 14. 16. 18. 20.]
  [22. 24. 26. 28. 30.]]]


In [17]:
print('a_array_325 ',a_array_325.shape, '\n', a_array_325)
print('b_array_325 ',b_array_325.shape, '\n', b_array_325)

a_array_325  (3, 2, 5) 
 [[[ 0.  1.  2.  3.  4.]
  [ 5.  6.  7.  8.  9.]]

 [[10. 12. 14. 16. 18.]
  [20. 22. 24. 26. 28.]]

 [[ 6.  8. 10. 12. 14.]
  [16. 18. 20. 22. 24.]]]
b_array_325  (3, 2, 5) 
 [[[50. 52. 54. 56. 58.]
  [60. 62. 64. 66. 68.]]

 [[30. 32. 34. 36. 38.]
  [40. 42. 44. 46. 48.]]

 [[12. 14. 16. 18. 20.]
  [22. 24. 26. 28. 30.]]]


In [18]:
a325_m_b325_rev = rev_a_325 * rev_b_325
print('a325_m_b325_rev:',a325_m_b325_rev.shape, '\n', a325_m_b325_rev)

a325_m_b325_rev: (3, 2, 5) 
 [[[   0.   52.  108.  168.  232.]
  [ 300.  372.  448.  528.  612.]]

 [[ 300.  384.  476.  576.  684.]
  [ 800.  924. 1056. 1196. 1344.]]

 [[  72.  112.  160.  216.  280.]
  [ 352.  432.  520.  616.  720.]]]


In [20]:
print('a235_m_b235:',a235_m_b235.shape, '\n', a235_m_b235)

a235_m_b235: (2, 3, 5) 
 [[[   0.   52.  108.  168.  232.]
  [ 300.  384.  476.  576.  684.]
  [  72.  112.  160.  216.  280.]]

 [[ 300.  372.  448.  528.  612.]
  [ 800.  924. 1056. 1196. 1344.]
  [ 352.  432.  520.  616.  720.]]]


In [40]:
ab325_avg = tf.reduce_sum(a325_m_b325_rev)/(2*3)
sess = tf.Session()
ab325_avg_v = sess.run(ab325_avg)
print('ab325_avg:\n', ab325_avg_v)
sess.close()

ab325_avg:
 2340.0


In [23]:
a25_list = []
b25_list = []
for ui in range(3):
    aui = np.array(rev_a_325[ui])
    a25_list.append(aui)
    bui = np.array(rev_b_325[ui])
    b25_list.append(bui)
print('a25_list:\n', a25_list)
print('b25_list:\n', b25_list)

a25_list:
 [array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.]]), array([[10., 12., 14., 16., 18.],
       [20., 22., 24., 26., 28.]]), array([[ 6.,  8., 10., 12., 14.],
       [16., 18., 20., 22., 24.]])]
b25_list:
 [array([[50., 52., 54., 56., 58.],
       [60., 62., 64., 66., 68.]]), array([[30., 32., 34., 36., 38.],
       [40., 42., 44., 46., 48.]]), array([[12., 14., 16., 18., 20.],
       [22., 24., 26., 28., 30.]])]


In [24]:
print('a25_list:\n', a25_list)
print()
print('a:\n', a)

a25_list:
 [array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.]]), array([[10., 12., 14., 16., 18.],
       [20., 22., 24., 26., 28.]]), array([[ 6.,  8., 10., 12., 14.],
       [16., 18., 20., 22., 24.]])]

a:
 [array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.]]), array([[10., 12., 14., 16., 18.],
       [20., 22., 24., 26., 28.]]), array([[ 6.,  8., 10., 12., 14.],
       [16., 18., 20., 22., 24.]])]


In [25]:
print('b25_list:\n', b25_list)
print()
print('b:\n', b)

b25_list:
 [array([[50., 52., 54., 56., 58.],
       [60., 62., 64., 66., 68.]]), array([[30., 32., 34., 36., 38.],
       [40., 42., 44., 46., 48.]]), array([[12., 14., 16., 18., 20.],
       [22., 24., 26., 28., 30.]])]

b:
 [array([[50., 52., 54., 56., 58.],
       [60., 62., 64., 66., 68.]]), array([[30., 32., 34., 36., 38.],
       [40., 42., 44., 46., 48.]]), array([[12., 14., 16., 18., 20.],
       [22., 24., 26., 28., 30.]])]


In [41]:
concat_a25_list = tf.concat(a25_list, 0)
concat_b25_list = tf.concat(b25_list, 0)
a25_m_b25_avg =tf.reduce_sum(concat_a25_list * concat_b25_list)/(3*2) 
sess = tf. Session()
cona25, conab25, a25mb25avg =sess.run([concat_a25_list,\
                               concat_b25_list,a25_m_b25_avg])
print('concat_a25_list:\n', cona25)
print('concat_b25_list:\n', conab25)
print('a25_m_b25_avg: ', a25mb25avg)
sess.close()

concat_a25_list:
 [[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 12. 14. 16. 18.]
 [20. 22. 24. 26. 28.]
 [ 6.  8. 10. 12. 14.]
 [16. 18. 20. 22. 24.]]
concat_b25_list:
 [[50. 52. 54. 56. 58.]
 [60. 62. 64. 66. 68.]
 [30. 32. 34. 36. 38.]
 [40. 42. 44. 46. 48.]
 [12. 14. 16. 18. 20.]
 [22. 24. 26. 28. 30.]]
a25_m_b25_avg:  2340.0


In [30]:
a325_hst = np.hstack(a_array_325)
a235 = np.reshape(a325_hst, (2, 3, 5))
print('a_array_325:', a_array_325.shape, '\n', a_array_325)
print()
print('a325_hst:', a325_hst.shape, '\n', a325_hst)
print()
print('a235:', a235.shape, '\n', a235)

a_array_325: (3, 2, 5) 
 [[[ 0.  1.  2.  3.  4.]
  [ 5.  6.  7.  8.  9.]]

 [[10. 12. 14. 16. 18.]
  [20. 22. 24. 26. 28.]]

 [[ 6.  8. 10. 12. 14.]
  [16. 18. 20. 22. 24.]]]

a325_hst: (2, 15) 
 [[ 0.  1.  2.  3.  4. 10. 12. 14. 16. 18.  6.  8. 10. 12. 14.]
 [ 5.  6.  7.  8.  9. 20. 22. 24. 26. 28. 16. 18. 20. 22. 24.]]

a235: (2, 3, 5) 
 [[[ 0.  1.  2.  3.  4.]
  [10. 12. 14. 16. 18.]
  [ 6.  8. 10. 12. 14.]]

 [[ 5.  6.  7.  8.  9.]
  [20. 22. 24. 26. 28.]
  [16. 18. 20. 22. 24.]]]


In [32]:
a235_hst = np.hstack(a235)
a325 = np.reshape(a235_hst, (3, 2, 5))
print('a235_hst:', a325_hst.shape, '\n', a235_hst)
print()
print('a325:', a325.shape, '\n', a325)
print()
print('a_array_325:', a_array_325.shape, '\n', a_array_325)


a235_hst: (2, 15) 
 [[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [10. 12. 14. 16. 18. 20. 22. 24. 26. 28.]
 [ 6.  8. 10. 12. 14. 16. 18. 20. 22. 24.]]

a325: (3, 2, 5) 
 [[[ 0.  1.  2.  3.  4.]
  [ 5.  6.  7.  8.  9.]]

 [[10. 12. 14. 16. 18.]
  [20. 22. 24. 26. 28.]]

 [[ 6.  8. 10. 12. 14.]
  [16. 18. 20. 22. 24.]]]

a_array_325: (3, 2, 5) 
 [[[ 0.  1.  2.  3.  4.]
  [ 5.  6.  7.  8.  9.]]

 [[10. 12. 14. 16. 18.]
  [20. 22. 24. 26. 28.]]

 [[ 6.  8. 10. 12. 14.]
  [16. 18. 20. 22. 24.]]]


In [34]:
print('a325 shape:', a325.shape)
print('a325 size axis 0:', np.size(a325 ,0))
print('a325 size axis 1:', np.size(a325 ,1))
print('a325 size axis 2:', np.size(a325 ,2))

a325 shape: (3, 2, 5)
a325 size axis 0: 3
a325 size axis 1: 2
a325 size axis 2: 5


In [46]:
# a25_m_b25_avg =tf.reduce_sum(concat_a25_list * concat_b25_list)/(3*2)
n_roll = len(a25_list)
batch_size = np.size(a25_list[0], 0)
axis_1 = np.size(a25_list[0], 1)
print('n_roll:', n_roll)
print('batch_size:', batch_size)
print('axis_1:', axis_1)

n_roll: 3
batch_size: 2
axis_1: 5


In [45]:
a25mb25avg=tf.reduce_sum(concat_a25_list*concat_b25_list)/(n_roll*batch_size)
with tf.Session() as sess:
    print('a25mb25avg:', a25mb25avg.eval())


a25mb25avg: 2340.0


In [47]:
a25_list_1= [np.array(rev_a_325[ui]) for ui in range(n_roll)]
b25_list_1= [np.array(rev_b_325[ui]) for ui in range(n_roll)]
print('a25_list_1:\n', a25_list_1)
print('b25_list_1:\n', b25_list_1)

print('a25_list:\n', a25_list)
print('b25_list:\n', b25_list)

a25_list_1:
 [array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.]]), array([[10., 12., 14., 16., 18.],
       [20., 22., 24., 26., 28.]]), array([[ 6.,  8., 10., 12., 14.],
       [16., 18., 20., 22., 24.]])]
b25_list_1:
 [array([[50., 52., 54., 56., 58.],
       [60., 62., 64., 66., 68.]]), array([[30., 32., 34., 36., 38.],
       [40., 42., 44., 46., 48.]]), array([[12., 14., 16., 18., 20.],
       [22., 24., 26., 28., 30.]])]
a25_list:
 [array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.]]), array([[10., 12., 14., 16., 18.],
       [20., 22., 24., 26., 28.]]), array([[ 6.,  8., 10., 12., 14.],
       [16., 18., 20., 22., 24.]])]
b25_list:
 [array([[50., 52., 54., 56., 58.],
       [60., 62., 64., 66., 68.]]), array([[30., 32., 34., 36., 38.],
       [40., 42., 44., 46., 48.]]), array([[12., 14., 16., 18., 20.],
       [22., 24., 26., 28., 30.]])]


In [77]:
x1 = tf.constant([[0., 1., 2., 3., 4.], [5., 6., 7., 8., 9.]])
x2 = tf.constant([[10., 12., 14., 16., 18.], [20., 22., 24., 26., 28.]])
x3 = tf.constant([[ 6.,  8., 10., 12., 14.], [16., 18., 20., 22., 24.]])                 
y1 = tf.constant([[50., 52., 54., 56., 58.], [60., 62., 64., 66., 68.]])
y2 = tf.constant([[30., 32., 34., 36., 38.], [40., 42., 44., 46., 48.]])
y3 = tf.constant([[12., 14., 16., 18., 20.], [22., 24., 26., 28., 30.]])
x = tf.stack([x1, x2, x3], axis=0)
x_list = [x1, x2, x3]
y = tf.stack([y1, y2, y3], axis=0)
y_list = [y1, y2, y3]
x_r325 = tf.reshape(x, [2, 3, 5])

#x_hs = tf.concat(x, 2)
#x_hs = tf.stack(tf.concat(x, 1), axis=1)
x_hs = tf.reshape(x, [-1, 5])
x_hs_235 = tf.reshape(x_hs, [2, 3, 5])

In [78]:
with tf.Session() as sess:
    x_v, x_list_v, y_v, y_list_v, x_r325_v,x_hs_v,x_hs_235_v = sess.run(
        [x, x_list, y, y_list, x_r325, x_hs, x_hs_235])
    print('x shape:', x_v.shape, 'x:\n', x_v)
    #print('x list:\n', x_list_v)
    #print('y shape:', y_v.shape, 'y:\n', y_v)
    #print('y list:\n', y_list_v)
    print('x_r325:\n', x_r325_v)
    print('x_hs:\n', x_hs_v)
    print('x_hs_235:\n', x_hs_235_v)

x shape: (3, 2, 5) x:
 [[[ 0.  1.  2.  3.  4.]
  [ 5.  6.  7.  8.  9.]]

 [[10. 12. 14. 16. 18.]
  [20. 22. 24. 26. 28.]]

 [[ 6.  8. 10. 12. 14.]
  [16. 18. 20. 22. 24.]]]
x_r325:
 [[[ 0.  1.  2.  3.  4.]
  [ 5.  6.  7.  8.  9.]
  [10. 12. 14. 16. 18.]]

 [[20. 22. 24. 26. 28.]
  [ 6.  8. 10. 12. 14.]
  [16. 18. 20. 22. 24.]]]
x_hs:
 [[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 12. 14. 16. 18.]
 [20. 22. 24. 26. 28.]
 [ 6.  8. 10. 12. 14.]
 [16. 18. 20. 22. 24.]]
x_hs_235:
 [[[ 0.  1.  2.  3.  4.]
  [ 5.  6.  7.  8.  9.]
  [10. 12. 14. 16. 18.]]

 [[20. 22. 24. 26. 28.]
  [ 6.  8. 10. 12. 14.]
  [16. 18. 20. 22. 24.]]]


In [107]:
x_us1_list = tf.unstack(x, axis=1)
x_us1_array = tf.stack(x_us1, axis=0)
x_us1_soft_list = [tf.nn.softmax(x_us1_list[ui]) for ui in range(2)]

In [108]:
with tf.Session() as sess:
    x_us1_list_v, x_us1_array_v, x_us1_soft_list_v = sess.run(
        [x_us1_list, x_us1_array, x_us1_soft_list])
        
    #print('x_us0:\n',x_us0_v)
    print('x_us1_list type:',type(x_us1_list_v),
          'x_us1_list[0] type:',x_us1_list_v[0].shape,'x_us1:\n',
          x_us1_list_v)
    print('x_us1_array type:',type(x_us1_array_v),
          'x_us1s shape:', x_us1_array_v.shape,'\n',x_us1_array_v)
    print('x_us1_soft_list type:',type(x_us1_soft_list_v),
          'x_us1_soft_list[0] shape:', x_us1_soft_list_v[0].shape,'\n',
          x_us1_soft_list_v)
    #print('x_us2:\n',x_us2_v)

x_us1_list type: <class 'list'> x_us1_list[0] type: (3, 5) x_us1:
 [array([[ 0.,  1.,  2.,  3.,  4.],
       [10., 12., 14., 16., 18.],
       [ 6.,  8., 10., 12., 14.]], dtype=float32), array([[ 5.,  6.,  7.,  8.,  9.],
       [20., 22., 24., 26., 28.],
       [16., 18., 20., 22., 24.]], dtype=float32)]
x_us1_array type: <class 'numpy.ndarray'> x_us1s shape: (2, 3, 5) 
 [[[ 0.  1.  2.  3.  4.]
  [10. 12. 14. 16. 18.]
  [ 6.  8. 10. 12. 14.]]

 [[ 5.  6.  7.  8.  9.]
  [20. 22. 24. 26. 28.]
  [16. 18. 20. 22. 24.]]]
x_us1_soft_list type: <class 'list'> x_us1_soft_list[0] shape: (3, 5) 
 [array([[1.1656231e-02, 3.1684920e-02, 8.6128540e-02, 2.3412165e-01,
        6.3640863e-01],
       [2.9007587e-04, 2.1433870e-03, 1.5837606e-02, 1.1702495e-01,
        8.6470395e-01],
       [2.9007587e-04, 2.1433870e-03, 1.5837606e-02, 1.1702495e-01,
        8.6470395e-01]], dtype=float32), array([[1.1656231e-02, 3.1684920e-02, 8.6128540e-02, 2.3412165e-01,
        6.3640863e-01],
       [2.9007587e-0

In [112]:
a1= np.array([[0., 1., 2., 3., 4.],  [5., 6., 7., 8., 9.]])
text_digt =[5, 7, 4, 8, 0]
text_digt[np.random.randint(0,5)]

8

In [118]:
#[np.random.randint(0, 100)]
predPhase_word = np.zeros((1, 1, 10),dtype=np.float32) 
predPhase_word[0, 0, text_digt[np.random.randint(0, 5)]] = 1.0
print(predPhase_word)

[[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]]


inputs.shape: (32, 10, 100)
rnn_cell.state_size: 128
initial_state.shape: (32, 128)


ValueError: Variable rnn/basic_rnn_cell/kernel already exists, disallowed. Did you mean to set reuse=True or reuse=tf.AUTO_REUSE in VarScope? Originally defined at:

  File "C:\Peter\Anaconda36\lib\site-packages\tensorflow\python\framework\ops.py", line 1740, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access
  File "C:\Peter\Anaconda36\lib\site-packages\tensorflow\python\framework\ops.py", line 3414, in create_op
    op_def=op_def)
  File "C:\Peter\Anaconda36\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
